### ISSUE TITLE
[Suggestion] Show program window if it's running

### ISSUE THREAD

**Issue by eduardomozart** [redddcyclone/glpi-agentmonitor#27]
The GLPI Agent is available on Start Menu (Windows), it would be great that if we open it and it's already running on background it opens the window instead of user thinking it's not working (it's running on taskbar), it only would not show up if it's enabled to start on Windows boot.

**Comment by redddcyclone** [comment]
Hi @eduardomozart 

Thanks for the suggestion, I've added this functionality for the next version. When you try to run another instance of the Monitor, the running instance window will be shown.

Though it is not perfect, because if the currently running instance of the Monitor is elevated (i.e. the Settings button or Start/Stop Service button has been clicked), it won't work unless the new instance is executed with elevation too.

Thanks a lot!
